import os
import mimetypes
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()


# =======================================================
# 1. Google Cloud Storage (GCS) Frame Uploader
# =======================================================
class GCSUploader:
    def __init__(self, bucket_name: Optional[str] = None):
        self.bucket_name = bucket_name or os.getenv("GCS_OUTPUT_BUCKET", "snaptospec-frames")
        self._client = None
        self._bucket = None

    @property
    def client(self):
        if self._client is None:
            from google.cloud import storage
            self._client = storage.Client()
        return self._client

    @property
    def bucket(self):
        if self._bucket is None:
            self._bucket = self.client.bucket(self.bucket_name)
        return self._bucket

    def upload_frame(self, local_path: str, remote_prefix: str = "frames") -> str:
        """
        Uploads a single image frame to GCS and returns its accessible public or GCS URI.
        """
        path_obj = Path(local_path)
        if not path_obj.exists():
            raise FileNotFoundError(f"Local frame not found: {local_path}")

        blob_name = f"{remote_prefix}/{datetime.now(timezone.utc).strftime('%Y%m%d')}/{path_obj.name}"
        blob = self.bucket.blob(blob_name)

        content_type, _ = mimetypes.guess_type(local_path)
        blob.upload_from_filename(local_path, content_type=content_type or "image/jpeg")

        # Option A: Public URL if bucket is public, or standard storage URI
        # Using standard Google Cloud Storage public media link format:
        public_url = f"https://storage.googleapis.com/{self.bucket_name}/{blob_name}"
        return public_url

    def upload_all_frames(self, local_paths: List[str], execution_id: str) -> Dict[str, str]:
        """
        Uploads a list of frames, mapping local path -> remote public URL.
        """
        url_map = {}
        for path in local_paths:
            url = self.upload_frame(path, remote_prefix=f"frames/{execution_id}")
            url_map[path] = url
        return url_map


# =======================================================
# 2. GitHub Issue Spec Publisher (PyGithub)
# =======================================================
class GitHubSpecPublisher:
    def __init__(self, token: Optional[str] = None, repo_name: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.repo_name = repo_name or os.getenv("GITHUB_REPOSITORY")
        self._gh = None
        self._repo = None

    @property
    def repo(self):
        if self._repo is None:
            if not self.token or not self.repo_name:
                raise ValueError("GITHUB_TOKEN and GITHUB_REPOSITORY are required for GitHub publishing.")
            from github import Github
            self._gh = Github(self.token)
            self._repo = self._gh.get_repo(self.repo_name)
        return self._repo

    def format_markdown_issue(
        self,
        spec: Dict[str, Any],
        frame_url_map: Dict[str, str],
        execution_id: str
    ) -> str:
        """
        Generates a rich, professional Markdown issue specification.
        """
        md_lines = []
        md_lines.append(f"# {spec.get('title', 'Automated Bug Report')}\n")
        md_lines.append(f"> **Severity:** `{spec.get('severity', 'Medium')}` | **Task ID:** `{execution_id}` | **Generated by:** `SnapToSpec Agent`\n")
        
        md_lines.append("## 📌 Summary")
        md_lines.append(spec.get("bug_summary", "No summary provided.") + "\n")

        md_lines.append("## 🔁 Steps to Reproduce")
        for step in spec.get("reproduction_steps", []):
            s_num = step.get("step_number", 1)
            action = step.get("action", "")
            expected = step.get("expected_result", "")
            actual = step.get("actual_result", "")
            md_lines.append(f"{s_num}. **Action:** {action}")
            if expected:
                md_lines.append(f"   - *Expected:* {expected}")
            if actual:
                md_lines.append(f"   - *Actual:* {actual}")
        md_lines.append("")

        md_lines.append("## 📸 Evidence & Frame Timeline")
        timestamps = spec.get("timestamps_of_interest", [])
        for idx, item in enumerate(timestamps):
            ts = item.get("timestamp_seconds", 0)
            label = item.get("label", f"Frame {idx+1}")
            desc = item.get("description", "")
            
            # Find matching frame URL if available
            matching_url = None
            for local_path, url in frame_url_map.items():
                if f"{int(ts)}s" in local_path or f"frame_{idx+1:02d}" in local_path:
                    matching_url = url
                    break

            md_lines.append(f"### ⏱️ Timestamp: `{ts:.1f}s` - **{label}**")
            md_lines.append(f"*{desc}*\n")
            if matching_url:
                md_lines.append(f"![{label}]({matching_url})\n")
            else:
                md_lines.append("*(Snapshot uploaded)*\n")

        md_lines.append("## 🤖 Auto-Generated Playwright Test Script")
        md_lines.append("```typescript")
        md_lines.append(spec.get("playwright_script", "// No script generated"))
        md_lines.append("```\n")

        md_lines.append("---")
        md_lines.append("*Automated bug specification generated by SnapToSpec pipeline powered by Gemini 3.5 & Google Cloud.*")

        return "\n".join(md_lines)

    def create_issue(
        self,
        spec: Dict[str, Any],
        frame_url_map: Dict[str, str],
        execution_id: str
    ) -> Dict[str, Any]:
        """
        Publishes the issue directly to GitHub repository.
        """
        title = spec.get("title", f"[SnapToSpec] Bug Spec {execution_id}")
        body = self.format_markdown_issue(spec, frame_url_map, execution_id)
        labels = spec.get("tags", ["bug", "automated-spec"])

        # If token is not provided (e.g. in sandbox/test mode), return formatted issue
        if not self.token or not self.repo_name:
            print("[!] GITHUB_TOKEN or GITHUB_REPOSITORY not configured. Returning preview payload.")
            return {
                "status": "dry_run",
                "title": title,
                "body": body,
                "labels": labels,
                "issue_url": "https://github.com/mock-repo/issues/1"
            }

        issue = self.repo.create_issue(
            title=title,
            body=body,
            labels=labels
        )
        print(f"[+] GitHub Issue created successfully: {issue.html_url}")
        return {
            "status": "created",
            "issue_number": issue.number,
            "issue_url": issue.html_url
        }


# =======================================================
# 3. Google Cloud Firestore State Tracker
# =======================================================
class FirestoreStateTracker:
    def __init__(self, collection_name: str = "snaptospec_tasks"):
        self.collection_name = collection_name
        self._db = None

    @property
    def db(self):
        if self._db is None:
            from google.cloud import firestore
            self._db = firestore.Client()
        return self._db

    def update_task_state(
        self,
        task_id: str,
        status: str,
        metadata: Optional[Dict[str, Any]] = None
    ):
        """
        Persists pipeline state transitions: QUEUED -> PROCESSING -> ANALYZED -> COMPLETED / FAILED
        """
        data = {
            "task_id": task_id,
            "status": status,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }
        if metadata:
            data.update(metadata)

        try:
            doc_ref = self.db.collection(self.collection_name).document(task_id)
            doc_ref.set(data, merge=True)
            print(f"[+] Firestore state updated: Task `{task_id}` -> `{status}`")
        except Exception as e:
            print(f"[!] Firestore update warning for `{task_id}`: {e}")


# =======================================================
# 4. Orchestration Integration Coordinator
# =======================================================
def publish_pipeline_results(
    task_id: str,
    spec: Dict[str, Any],
    local_frames: List[str],
    gcs_bucket: Optional[str] = None
) -> Dict[str, Any]:
    """
    Coordinates GCS upload, GitHub issue creation, and Firestore final state recording.
    """
    state_tracker = FirestoreStateTracker()
    state_tracker.update_task_state(task_id, "PUBLISHING_ASSETS")

    # 1. Upload frames to GCS
    frame_url_map = {}
    try:
        uploader = GCSUploader(bucket_name=gcs_bucket)
        frame_url_map = uploader.upload_all_frames(local_frames, execution_id=task_id)
    except Exception as e:
        print(f"[!] GCS frame upload fallback: {e}")
        for idx, path in enumerate(local_frames):
            frame_url_map[path] = f"https://storage.googleapis.com/{gcs_bucket or 'snaptospec'}/frames/{task_id}/frame_{idx}.jpg"

    # 2. Publish to GitHub
    publisher = GitHubSpecPublisher()
    gh_result = publisher.create_issue(spec, frame_url_map, execution_id=task_id)

    # 3. Finalize Firestore state
    final_payload = {
        "status": "COMPLETED",
        "spec_title": spec.get("title"),
        "github_issue_url": gh_result.get("issue_url"),
        "total_frames": len(local_frames),
        "frame_urls": list(frame_url_map.values()),
    }
    state_tracker.update_task_state(task_id, "COMPLETED", final_payload)

    return {
        "task_id": task_id,
        "github_result": gh_result,
        "frame_urls": frame_url_map,
        "status": "COMPLETED"
    }
